/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTreatmentsRouteImport } from './routes/_app/treatments'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppStocksRouteImport } from './routes/_app/stocks'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppPeripheralsRouteImport } from './routes/_app/peripherals'
import { Route as AppPaymentMethodsRouteImport } from './routes/_app/payment-methods'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreatmentsRoute = AppTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStocksRoute = AppStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeripheralsRoute = AppPeripheralsRouteImport.update({
  id: '/peripherals',
  path: '/peripherals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentMethodsRoute = AppPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/payment-methods': typeof AppPaymentMethodsRoute
  '/peripherals': typeof AppPeripheralsRoute
  '/purchases': typeof AppPurchasesRoute
  '/report': typeof AppReportRoute
  '/reservations': typeof AppReservationsRoute
  '/sales': typeof AppSalesRoute
  '/staff': typeof AppStaffRoute
  '/stocks': typeof AppStocksRoute
  '/support': typeof AppSupportRoute
  '/treatments': typeof AppTreatmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/payment-methods': typeof AppPaymentMethodsRoute
  '/peripherals': typeof AppPeripheralsRoute
  '/purchases': typeof AppPurchasesRoute
  '/report': typeof AppReportRoute
  '/reservations': typeof AppReservationsRoute
  '/sales': typeof AppSalesRoute
  '/staff': typeof AppStaffRoute
  '/stocks': typeof AppStocksRoute
  '/support': typeof AppSupportRoute
  '/treatments': typeof AppTreatmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/payment-methods': typeof AppPaymentMethodsRoute
  '/_app/peripherals': typeof AppPeripheralsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/report': typeof AppReportRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/stocks': typeof AppStocksRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/treatments': typeof AppTreatmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/dashboard'
    | '/patients'
    | '/payment-methods'
    | '/peripherals'
    | '/purchases'
    | '/report'
    | '/reservations'
    | '/sales'
    | '/staff'
    | '/stocks'
    | '/support'
    | '/treatments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/dashboard'
    | '/patients'
    | '/payment-methods'
    | '/peripherals'
    | '/purchases'
    | '/report'
    | '/reservations'
    | '/sales'
    | '/staff'
    | '/stocks'
    | '/support'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/accounts'
    | '/_app/dashboard'
    | '/_app/patients'
    | '/_app/payment-methods'
    | '/_app/peripherals'
    | '/_app/purchases'
    | '/_app/report'
    | '/_app/reservations'
    | '/_app/sales'
    | '/_app/staff'
    | '/_app/stocks'
    | '/_app/support'
    | '/_app/treatments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/treatments': {
      id: '/_app/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof AppTreatmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stocks': {
      id: '/_app/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AppStocksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/peripherals': {
      id: '/_app/peripherals'
      path: '/peripherals'
      fullPath: '/peripherals'
      preLoaderRoute: typeof AppPeripheralsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/payment-methods': {
      id: '/_app/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AppPaymentMethodsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPaymentMethodsRoute: typeof AppPaymentMethodsRoute
  AppPeripheralsRoute: typeof AppPeripheralsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportRoute: typeof AppReportRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStocksRoute: typeof AppStocksRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTreatmentsRoute: typeof AppTreatmentsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPaymentMethodsRoute: AppPaymentMethodsRoute,
  AppPeripheralsRoute: AppPeripheralsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportRoute: AppReportRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSalesRoute: AppSalesRoute,
  AppStaffRoute: AppStaffRoute,
  AppStocksRoute: AppStocksRoute,
  AppSupportRoute: AppSupportRoute,
  AppTreatmentsRoute: AppTreatmentsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
